server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/delivery_db
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    mappings:
      enabled: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.boot: DEBUG
